In [20]:
#a
import numpy as np


In [21]:
#b
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#c
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
#d
c = b*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [24]:
#e
d = np.arange(10, 51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [26]:
#f
f = np.arange(10, 51, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [80]:
#g
g = np.arange(0, 9).reshape(3, 3)
print(gn)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
#h 
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
#i 
i = np.random.rand(1)
print(i)

[0.80577871]


In [135]:
#j
j = np.random.rand(25)
print(j)

[0.05620305 0.10682122 0.13360569 0.80895358 0.36771348 0.44224597
 0.20513896 0.01583783 0.79384671 0.86360714 0.96490282 0.11635335
 0.53479972 0.92709735 0.5492453  0.97709926 0.91566843 0.93714359
 0.6495919  0.38936019 0.16405868 0.48617794 0.68434164 0.24970739
 0.7277151 ]


In [78]:
#k
k = np.arange(0, 1.01, 0.01)
print(k)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [96]:

mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [100]:
#l
print('l =', mat[2:, 1:])

l = [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [114]:
#m
ar = mat[mat == 20]
print(ar)

[20]


In [112]:
#n
print('n =', mat[0:3, 1].reshape(3,1))

n = [[ 2]
 [ 7]
 [12]]


In [111]:
#o
print('o =', mat[3,4])

o = 20


In [117]:
#p
print('p =', mat[3:])

p = [[16 17 18 19 20]
 [21 22 23 24 25]]


In [119]:
#q
print(mat.sum())

325


In [120]:
#r
print(mat.std())

7.211102550927978


In [130]:
#s
print(mat.sum(axis=0))

[55 60 65 70 75]
